name: final_year_project
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dependencies:
  api_cache_manager: ^1.0.2
  snippet_coder_utils: ^1.0.12
  http: ^0.13.4
  provider:
  shared_preferences: ^2.0.13
  intl: ^0.17.0
  url_launcher: ^6.0.20
  flutter_staggered_grid_view: ^0.6.1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
