name: final_year_project
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dependencies:
  api_cache_manager: ^1.0.2
  snippet_coder_utils: ^1.0.9
  http: ^0.13.4
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  flutter_riverpod: ^1.0.3
  provider:

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  freezed: ^1.1.1
  json_serializable: ^6.1.4
  

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
